project:
  name: microservice-cloud bestline
application:
  name: ark application
  enc: '{cipher}AQA/E90CenbeCMkThMMxiY8d77AcrEVea0EvHNx9yerwNaZhS9iJG9HWjXDiPeFKJtmPqnWM4yQD8kYcRvb+ls7ye72mZ7+kESTiTxK6Bk56pduJcPkpycwZpBGnrWs7KXsm156KXjk0JWtQtJ6qjPbx70yX9EaOb+hP+xOimmcvosUcUAK6R3WBuY4xxlGRGiWqZJYp4KOnSh9LM7jc4tHTfYuxU3dz7+5T5v/BGmEcghP0FCWZJEqlQEU2CDhVKPuGx6QJud2Z81U4bFeS3yuqQothV8OclOLoVe0NFpjHI5HuDxH/EKpWXVEbtk2kleyv33BpSJJLG5DvBCD9QMQ4fokq+PQtwkaTGfu1xCJvx7+tOjaIp5ApG697DQr7nDQ='
